import {questions,dimensionLabels} from './questions.js';
import {scoreChemistry,buildNarrative} from './scoring.js';
import {selectChallenges,drawChallenge} from './challenges.js';
import {sessionClient,nativeShare,copyText,tokenFromPath} from './session.js';

const app=document.querySelector('#app');
const state={mode:'home',name:'',index:0,answers:{},session:null,locked:false,result:null,drawn:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const optionLabel=(q,v)=>Array.isArray(v)?v.map(i=>q.options[i]).join(', '):q.options[v];

function button(label,cls='btn-primary',attrs=''){return `<button class="btn ${cls}" ${attrs}>${label}</button>`}
function home(){app.innerHTML=`<section class="screen"><p class="eyebrow">Private two-person chemistry test</p><h1 class="brand">NO<br>WARNING</h1><div class="subtitle">THE CHEMISTRY TEST</div><p class="lede">40 questions. Two people. No peeking. One reveal.</p><div class="stack">${button('TAKE THE TEST','','data-action="start"')}${button('I HAVE A SHARE LINK','btn-secondary','data-action="share-entry"')}</div><div class="tagline">FLIP IT. FIND OUT.</div></section>`}
function nameScreen(player=1){app.innerHTML=`<section class="screen"><div class="card"><p class="eyebrow">Player ${player}</p><h2 class="lock-copy">WHO'S OWNING THESE ANSWERS?</h2><p class="muted">Use a first name or nickname. Nothing else is needed.</p><input class="input" id="name" maxlength="32" autocomplete="nickname" placeholder="Name or nickname" value="${esc(state.name)}"><div class="stack">${button(player===1?'START THE TEST':'START MY TEST','','data-action="name-next"')}</div></div></section>`}
function questionScreen(){const q=questions[state.index],ans=state.answers[q.id],pct=Math.round((state.index/questions.length)*100);const multi=q.type==='multi';app.innerHTML=`<section class="screen"><div class="topbar"><button class="btn btn-ghost" data-action="back" ${state.index===0?'disabled':''}>← BACK</button><div class="progress-wrap"><div class="progress-label"><span>${esc(q.section)}</span><span>${state.index+1} / ${questions.length}</span></div><div class="progress"><span style="width:${pct}%"></span></div></div></div><div class="card"><div class="section">${esc(q.section)} · ${q.type==='wyr'?'WOULD YOU RATHER':q.type==='situational'?'SITUATIONAL CHOICE':multi?'SELECT ALL THAT APPLY':'MULTIPLE CHOICE'}</div><h2 class="question">${esc(q.prompt)}</h2>${multi?'<div class="hint">Choose every answer that fits.</div>':''}<div class="options">${q.options.map((o,i)=>{const sel=multi?Array.isArray(ans)&&ans.includes(i):ans===i;return `<button class="option ${sel?'selected':''}" data-action="option" data-index="${i}" aria-pressed="${sel}">${esc(o)}</button>`}).join('')}</div><div class="navrow">${button(state.index===questions.length-1?'LOCK IT IN':'OWN IT →','','data-action="next"')}</div></div></section>`}
function preLock(){app.innerHTML=`<section class="screen"><div class="card"><p class="eyebrow">Final check</p><h2 class="lock-copy">READY TO OWN IT?</h2><p class="lede">Once you lock these answers, you cannot change them. Player 2 will never see them before they submit their own.</p><div class="stack">${button('LOCK IT IN','','data-action="lock"')}${button('GO BACK','btn-secondary','data-action="back-question"')}</div></div></section>`}
function linksScreen(){const origin=location.origin+location.pathname;const share=`${origin}?share=${encodeURIComponent(state.session.shareToken)}`;const reveal=`${origin}?reveal=${encodeURIComponent(state.session.revealToken)}`;app.innerHTML=`<section class="screen"><div class="card"><p class="eyebrow">Answers locked</p><h2 class="lock-copy">YOUR MOVE IS DONE.</h2><p class="muted">Send the Share Link to Player 2. Keep the Reveal Link for the final flip.</p><div class="result-section"><h3>Share link</h3><div class="linkbox"><code>${esc(share)}</code></div><div class="share-row">${button('SHARE','btn-primary','data-action="share-share"')}${button('COPY','btn-secondary','data-action="copy-share"')}</div></div><div class="result-section"><h3>Reveal link</h3><div class="linkbox"><code>${esc(reveal)}</code></div><div class="share-row">${button('SHARE','btn-primary','data-action="share-reveal"')}${button('COPY','btn-secondary','data-action="copy-reveal"')}</div></div><div class="boundary"><strong>THEY HAVEN’T OWNED IT YET.</strong><br>Your answers are locked. Their move.</div></div></section>`}
function waiting(){app.innerHTML=`<section class="screen"><div class="card"><p class="eyebrow">Reveal locked</p><h2 class="lock-copy">THEY HAVEN’T OWNED IT YET.</h2><p class="lede">Your answers are locked. Their move.</p><div class="tagline">FLIP IT. FIND OUT.</div></div></section>`}
function revealReady(data){app.innerHTML=`<section class="screen"><div class="card"><p class="eyebrow">Both players submitted</p><h2 class="lock-copy">BOTH ANSWERS ARE LOCKED.</h2><p class="lede">No changing them.<br>No explaining them away.</p><div class="tagline">FLIP IT. FIND OUT.</div><div class="stack">${button('REVEAL OUR CHEMISTRY →','','data-action="show-results"')}</div></div></section>`;state.result=data}
function results(){const data=state.result;const result=data.result||scoreChemistry(questions,data.player1.answers,data.player2.answers);const narrative=data.narrative||buildNarrative(result,questions,data.player1.answers,data.player2.answers);const challenges=data.challenges||selectChallenges(result.dimensions,5);const compare=(data.comparisons||result.details.sort((a,b)=>Math.abs(.5-b.score)-Math.abs(.5-a.score)).slice(0,4).map(d=>{const q=questions.find(x=>x.id===d.questionId);return {q:q.prompt,a:optionLabel(q,data.player1.answers[q.id]),b:optionLabel(q,data.player2.answers[q.id])}}));app.innerHTML=`<section class="screen" style="justify-content:flex-start"><p class="eyebrow">${esc(data.player1.name)} + ${esc(data.player2.name)}</p><div class="score">${result.overall}%</div><h2 class="lock-copy">${esc(result.title)}</h2><p class="muted">Descriptive chemistry, not a prediction of relationship success.</p><div class="dimensions">${Object.entries(dimensionLabels).map(([k,l])=>`<div class="dim"><span>${l}</span><strong>${result.dimensions[k]}%</strong></div>`).join('')}</div>${section('YOUR DYNAMIC',narrative.dynamic)}${section('THE MATCH',narrative.match)}${section('THE SWITCH-UP',narrative.switchUp)}${section('NO WARNING DISCOVERY',narrative.discovery)}<div class="result-section"><h3>YOU SAID / THEY SAID</h3>${compare.map(x=>`<div class="challenge"><strong>${esc(x.q)}</strong><div>${esc(data.player1.name)}: ${esc(x.a)}</div><div>${esc(data.player2.name)}: ${esc(x.b)}</div></div>`).join('')}</div><div class="result-section"><h3>🔥 PLAY IT OUT</h3>${challenges.map(c=>challengeCard(c)).join('')}<div class="boundary"><strong>HARD PASS ALWAYS OVERRIDES THE CHALLENGE.</strong><br>Either person can pass. No penalty. No explanation required.<br><br>Chemistry is encouraged. Pressure isn’t.</div></div><div class="result-section"><h3>🃏 DRAW ANOTHER</h3><p class="muted">You will not know the media type or challenge until it appears.</p>${button('DRAW MY CHALLENGE','','data-action="draw"')}<div id="drawn"></div></div></section>`}
const section=(h,p)=>`<div class="result-section"><h3>${h}</h3><p class="lede">${esc(p)}</p></div>`;
const challengeCard=c=>`<div class="challenge"><strong>${esc(c.media)} — ${esc(c.title)}</strong><div>${esc(c.text)}</div></div>`;
function errorScreen(msg){app.innerHTML=`<section class="screen"><div class="card"><div class="error"><strong>NO WARNING hit a snag.</strong><br>${esc(msg)}</div><div class="stack">${button('BACK TO START','btn-secondary','data-action="home"')}</div></div></section>`}

async function beginPlayer1(){state.mode='p1';state.index=0;state.answers={};nameScreen(1)}
async function openShare(){const token=tokenFromPath('share');if(!token)return errorScreen('Missing Share Link session.');try{const s=await sessionClient.loadShare(token);if(s.completed)return errorScreen('This test has already been completed.');state.session={shareToken:token,...s};state.mode='p2';state.index=0;state.answers={};nameScreen(2)}catch(e){errorScreen(e.message.includes('404')?'Invalid or expired Share Link.':e.message)}}
async function openReveal(){const token=tokenFromPath('reveal');if(!token)return errorScreen('Missing Reveal Link session.');try{const r=await sessionClient.loadReveal(token);if(!r.ready)return waiting();revealReady(r)}catch(e){errorScreen(e.message)}}

app.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;
 if(a==='start')return beginPlayer1();if(a==='home'){history.replaceState({},'',location.pathname);return home()}if(a==='share-entry'){const t=prompt('Paste the Share Link or token');if(!t)return;try{const u=new URL(t,location.href);history.replaceState({},'',`${location.pathname}?share=${encodeURIComponent(u.searchParams.get('share')||t)}`);return openShare()}catch{return errorScreen('That Share Link is not valid.')}}
 if(a==='name-next'){const v=document.querySelector('#name')?.value.trim();if(!v)return;state.name=v;questionScreen();return}
 if(a==='option'){const q=questions[state.index],i=Number(el.dataset.index);if(q.type==='multi'){const arr=Array.isArray(state.answers[q.id])?[...state.answers[q.id]]:[];const p=arr.indexOf(i);p>=0?arr.splice(p,1):arr.push(i);state.answers[q.id]=arr}else state.answers[q.id]=i;questionScreen();return}
 if(a==='back'){if(state.index>0)state.index--;questionScreen();return}
 if(a==='next'){const q=questions[state.index],ans=state.answers[q.id];if(ans==null||(q.type==='multi'&&ans.length===0))return;if(state.index===questions.length-1)return preLock();state.index++;questionScreen();return}
 if(a==='back-question'){questionScreen();return}
 if(a==='lock'){try{if(state.mode==='p1'){const c=await sessionClient.create(state.name);await sessionClient.submitPlayer1(c.sessionId,c.player1Token,state.name,state.answers);state.session=c;linksScreen()}else{await sessionClient.submitPlayer2(state.session.shareToken,state.name,state.answers);history.replaceState({},'',`${location.pathname}?reveal=${encodeURIComponent(state.session.revealToken||'')}`);app.innerHTML=`<section class="screen"><div class="card"><h2 class="lock-copy">LOCKED.</h2><p class="lede">Your answers are in. Use the Reveal Link from Player 1 to flip the chemistry.</p></div></section>`}}catch(err){errorScreen(err.message)}return}
 if(a==='share-share'||a==='copy-share'||a==='share-reveal'||a==='copy-reveal'){const base=location.origin+location.pathname;const isShare=a.includes('share')&&!a.includes('reveal');const url=isShare?`${base}?share=${state.session.shareToken}`:`${base}?reveal=${state.session.revealToken}`;if(a.startsWith('share-'))await nativeShare('NO WARNING — The Chemistry Test','40 questions. Two people. No peeking. One reveal.',url);else await copyText(url);el.textContent='COPIED';return}
 if(a==='show-results'){results();return}
 if(a==='draw'){const d=drawChallenge(state.result.result?.dimensions||state.result.dimensions||{},state.drawn);if(!d)return;state.drawn.push(d.id);document.querySelector('#drawn').innerHTML=challengeCard(d)+button('DRAW AGAIN','btn-secondary','data-action="draw"');return}
});

(async()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(tokenFromPath('share'))return openShare();if(tokenFromPath('reveal'))return openReveal();home()})();
