export const sections=["First Spark","Flirting","Physical Chemistry","Mental & Emotional Chemistry","Spontaneity & Boldness","No Warning"];

// Centralized, editable test bank. Replace wording/options here without touching UI or scoring.
// `similarity` rewards aligned preferences. `complements` maps strong role-pair matches.
// Q37–40 carry 1.2x weight by default.
export const questions=[
{id:1,section:"First Spark",type:"single",prompt:"What usually creates the first real spark for you?",options:["Eye contact that lingers","Easy conversation","Playful teasing","Physical presence","A surprising shared interest"],dimensions:["attraction","mental"],weight:1},
{id:2,section:"First Spark",type:"single",prompt:"When you are interested in someone, what gives you away first?",options:["I make more eye contact","I find reasons to talk to them","I tease them more","I get a little quieter","I become more physically expressive"],dimensions:["flirting","tension"],weight:1},
{id:3,section:"First Spark",type:"wyr",prompt:"Would you rather feel an instant spark or a slow-building pull?",options:["Instant spark","Slow-building pull"],dimensions:["attraction","connection"],weight:1},
{id:4,section:"First Spark",type:"single",prompt:"What makes somebody immediately more attractive to you?",options:["Confidence","Humor","Warmth","Mystery","Intelligence"],dimensions:["attraction","mental"],weight:1},
{id:5,section:"First Spark",type:"multi",prompt:"Which signs make you think chemistry might be mutual?",options:["Longer eye contact","Fast replies","Inside jokes","Finding excuses to be close","Remembering small details","Playful physical contact"],dimensions:["flirting","tension","connection"],weight:1},
{id:6,section:"First Spark",type:"situational",prompt:"You meet someone and the vibe is unexpectedly strong. What is your instinct?",options:["Lean into it immediately","Keep it playful and test the vibe","Stay composed and let them show interest first","Slow down and learn more about them"],dimensions:["spontaneity","flirting"],weight:1,complements:[[0,2],[2,0]]},
{id:7,section:"First Spark",type:"single",prompt:"How important is physical attraction at the very beginning?",options:["It is essential","Very important","Important but not enough by itself","Nice, but connection matters more","It can grow later"],dimensions:["attraction","connection"],weight:1},
{id:8,section:"Flirting",type:"single",prompt:"Your natural flirting style is closest to…",options:["Direct","Playful","Subtle","Bold","I make them wonder"],dimensions:["flirting","tension"],weight:1},
{id:9,section:"Flirting",type:"situational",prompt:"The conversation gets flirty over text. What do you do?",options:["Turn it up","Match their energy","Drop one bold line and disappear","Keep it teasing but controlled","Wait for them to push it further"],dimensions:["flirting","tension","spontaneity"],weight:1,complements:[[0,4],[4,0],[2,3],[3,2]]},
{id:10,section:"Flirting",type:"wyr",prompt:"Would you rather receive a bold compliment or a subtle one that takes a second to register?",options:["Bold compliment","Subtle compliment"],dimensions:["flirting","affection"],weight:1},
{id:11,section:"Flirting",type:"multi",prompt:"What kind of flirting works on you?",options:["Teasing","Compliments","Eye contact","Playful challenges","Voice notes","Suggestive jokes","Unexpected check-ins"],dimensions:["flirting","tension","affection"],weight:1},
{id:12,section:"Flirting",type:"single",prompt:"Who should usually make the first move?",options:["Me","Them","Whoever feels it first","I like a back-and-forth buildup"],dimensions:["flirting","tension"],weight:1.1,complements:[[0,1],[1,0]]},
{id:13,section:"Flirting",type:"single",prompt:"How much do you enjoy anticipation?",options:["A lot — the buildup is half the fun","Some — but do not drag it out","A little — I prefer directness","Not much — just say what you mean"],dimensions:["tension","flirting"],weight:1},
{id:14,section:"Flirting",type:"situational",prompt:"They send a message that clearly has a double meaning. Your move?",options:["Answer with an even better double meaning","Pretend not to notice, then circle back later","Call it out directly","Send an emoji and make them work for it"],dimensions:["flirting","spontaneity","tension"],weight:1},
{id:15,section:"Physical Chemistry",type:"single",prompt:"What creates the most physical tension for you?",options:["Eye contact","Being close without touching","A confident touch","A low voice or whisper","Knowing the attraction is mutual"],dimensions:["tension","attraction"],weight:1.1},
{id:16,section:"Physical Chemistry",type:"multi",prompt:"Which kinds of affection feel naturally good to you?",options:["Holding hands","Hugs","Kissing","Cuddling","Touching an arm or back","Sitting close","Playful physical contact"],dimensions:["affection","attraction"],weight:1},
{id:17,section:"Physical Chemistry",type:"single",prompt:"How much does scent influence attraction for you?",options:["A lot","More than people realize","Somewhat","Not much","Almost not at all"],dimensions:["attraction"],weight:.8},
{id:18,section:"Physical Chemistry",type:"wyr",prompt:"Would you rather have intense eye contact or effortless physical closeness?",options:["Intense eye contact","Effortless physical closeness"],dimensions:["tension","affection"],weight:1},
{id:19,section:"Physical Chemistry",type:"situational",prompt:"You are sitting close and neither person moves away. What feels most natural?",options:["Let the tension build","Close the distance","Say something playful about it","Wait for them to make the move"],dimensions:["tension","attraction","flirting"],weight:1.1,complements:[[1,3],[3,1]]},
{id:20,section:"Physical Chemistry",type:"single",prompt:"Your ideal physical chemistry feels…",options:["Electric","Warm and affectionate","Playful","Slow and intense","Natural and effortless"],dimensions:["attraction","affection","tension"],weight:1},
{id:21,section:"Physical Chemistry",type:"single",prompt:"How comfortable are you with affectionate public touch?",options:["Very comfortable","Comfortable in small doses","Depends on the setting","Mostly private","Very private"],dimensions:["affection"],weight:.9},
{id:22,section:"Mental & Emotional Chemistry",type:"single",prompt:"What makes conversation feel addictive?",options:["Humor","Depth","Curiosity","Fast banter","Feeling understood"],dimensions:["mental","connection"],weight:1.1},
{id:23,section:"Mental & Emotional Chemistry",type:"multi",prompt:"Which things make you feel emotionally close to someone?",options:["Honest conversations","Consistency","Shared humor","Feeling desired","Being listened to","Doing new things together","Quiet comfort"],dimensions:["connection","mental","affection"],weight:1},
{id:24,section:"Mental & Emotional Chemistry",type:"wyr",prompt:"Would you rather be with someone who challenges your thinking or instantly understands your thinking?",options:["Challenges my thinking","Understands my thinking"],dimensions:["mental","connection"],weight:1},
{id:25,section:"Mental & Emotional Chemistry",type:"single",prompt:"How important is being able to talk about almost anything?",options:["Essential","Very important","Important","Nice to have","Not a major factor"],dimensions:["mental","connection"],weight:1},
{id:26,section:"Mental & Emotional Chemistry",type:"situational",prompt:"You disagree on something meaningful. What kind of response draws you closer?",options:["Calm debate","Curious questions","A little humor first","Direct honesty followed by reassurance","Space, then a real conversation"],dimensions:["mental","connection"],weight:1.1},
{id:27,section:"Mental & Emotional Chemistry",type:"single",prompt:"What feels more intimate to you?",options:["Being fully understood","Being physically close","Being trusted with something vulnerable","Laughing until you cannot breathe","Being chosen consistently"],dimensions:["connection","mental","affection"],weight:1},
{id:28,section:"Mental & Emotional Chemistry",type:"multi",prompt:"What makes you feel wanted without somebody saying it directly?",options:["They initiate conversation","They remember details","They make time for me","Their body language changes around me","They check on me","They flirt with intention"],dimensions:["connection","flirting","affection"],weight:1},
{id:29,section:"Spontaneity & Boldness",type:"single",prompt:"How spontaneous are you when the vibe is right?",options:["Very — I will change the plan","Pretty spontaneous","Depends on the person","I prefer some warning","I like a plan"],dimensions:["spontaneity"],weight:1},
{id:30,section:"Spontaneity & Boldness",type:"situational",prompt:"They text: “Be ready in an hour. I have an idea.” Your reaction?",options:["Say less. I am ready.","Ask one question, then go","Need a few details first","Suggest planning it for another time"],dimensions:["spontaneity","tension"],weight:1},
{id:31,section:"Spontaneity & Boldness",type:"wyr",prompt:"Would you rather plan an unforgettable night or let an ordinary night unexpectedly become unforgettable?",options:["Plan it","Let it happen unexpectedly"],dimensions:["spontaneity","connection"],weight:1},
{id:32,section:"Spontaneity & Boldness",type:"multi",prompt:"Which spontaneous moves sound exciting with the right person?",options:["Late-night drive","Unexpected date","Random voice note","Surprise visit when invited","Trying somewhere new","Sending a daring message","Changing plans on the spot"],dimensions:["spontaneity","flirting"],weight:1},
{id:33,section:"Spontaneity & Boldness",type:"single",prompt:"When attraction is obvious, how bold are you willing to be?",options:["Very bold","Bold if they are matching me","Playfully bold","More subtle than bold","I need them to lead"],dimensions:["spontaneity","flirting","tension"],weight:1.1,complements:[[0,4],[4,0],[1,3],[3,1]]},
{id:34,section:"Spontaneity & Boldness",type:"situational",prompt:"You both keep hinting at something but nobody says it outright. What should happen next?",options:["Someone should just say it","Keep teasing until one person breaks","Ask a direct question","Let actions answer it"],dimensions:["spontaneity","tension","flirting"],weight:1},
{id:35,section:"Spontaneity & Boldness",type:"single",prompt:"What makes a bold move attractive instead of too much?",options:["Confidence","Timing","Mutual signals","Humor","Respect for boundaries"],dimensions:["spontaneity","connection"],weight:1},
{id:36,section:"Spontaneity & Boldness",type:"single",prompt:"How much do you enjoy being surprised by someone you trust?",options:["A lot","Usually","Sometimes","Only with some warning","I prefer knowing the plan"],dimensions:["spontaneity","connection"],weight:1},
{id:37,section:"No Warning",type:"situational",prompt:"No warning: they admit they have been thinking about you differently lately. What response feels most like you?",options:["Tell them exactly where I stand","Make them explain what “differently” means","Tease them before admitting anything","If I feel it too, I make that obvious","I need a minute before answering"],dimensions:["flirting","connection","tension"],weight:1.2},
{id:38,section:"No Warning",type:"single",prompt:"What kind of chemistry is hardest for you to ignore?",options:["Physical tension","Mental connection","Playful flirting","Emotional closeness","All of it hitting at once"],dimensions:["attraction","mental","flirting","connection","tension"],weight:1.2},
{id:39,section:"No Warning",type:"multi",prompt:"Which things would make you think, “Okay… this might actually be something”?",options:["The flirting feels different","We talk for hours without trying","The physical tension is obvious","We keep choosing each other","We are unusually comfortable together","We bring out a bolder side in each other"],dimensions:["flirting","mental","attraction","connection","spontaneity"],weight:1.2},
{id:40,section:"No Warning",type:"situational",prompt:"Final one. The chemistry is clearly mutual. What happens next in your ideal version of this story?",options:["We say it directly and see where it goes","We plan a real date","We keep the tension alive and let it unfold","We have an honest conversation about what this is","We stop overthinking and make a move"],dimensions:["connection","flirting","spontaneity","tension"],weight:1.25,complements:[[1,4],[4,1],[0,3],[3,0]]}
];

export const dimensionLabels={attraction:"🔥 Attraction",flirting:"😏 Flirting",tension:"👀 Tension",affection:"💋 Affection",mental:"🧠 Mental Chemistry",connection:"❤️ Connection",spontaneity:"🎲 Spontaneity"};
