(()=>{'use strict';
const BANK={
Communication:[['💬 SAY IT STRAIGHT','Each gets two sentences: “When I need to feel heard, I need…” and “One thing that shuts me down is…” Then swap.'],['🎙️ SOFTER SIGNAL','Send each other a 20-second voice note saying something you appreciate about how the other communicates—then one thing you want more of.']],
Trust:[['🔐 TRUST DEPOSIT','Each name one small, realistic action the other can do this week that makes trust feel easier. Keep it specific and doable.'],['👀 NO-GUESSING GAME','Each finish: “I feel most secure with you when…” No defending or explaining until both answers are out.']],
Affection:[['💕 PICK YOUR SIGNAL','Separately choose your favorite everyday affection signal: touch, words, thoughtful gesture, quality time, or playful attention. Reveal together and use both this week.'],['📸 SOFT LAUNCH','Send a photo, GIF, or meme that captures the kind of affection you wish showed up a little more often. Explain only after your partner guesses.']],
Lifestyle:[['📅 PERFECT 3 HOURS','You each get three imaginary free hours together. Plan them separately in three beats, reveal, then build one date using the best parts of both.'],['🎲 YOUR TURN / MY TURN','Each pick one low-effort thing you genuinely enjoy. Put both into one mini-date: your thing first, their thing second.']],
Future:[['🧭 SAME MAP?','Each privately finish: “In the next year, I hope we…” Reveal at the same time and find one goal you can actively support together.'],['✨ SOMEDAY / SOON / NOT ME','Take three relationship ideas—travel, home, family, career move, commitment milestone—and each label them Someday, Soon, or Not Me. Compare without negotiating.']],
Conflict:[['🧯 RESET BUTTON','Each choose the phrase you would most want to hear when tension rises: “I’m listening,” “Give me a minute,” “We’re on the same team,” or write your own. Save each other’s answer.'],['🤝 REPAIR REHEARSAL','Pick a harmless past disagreement. Each gets one minute to say what would have helped the moment end better—without reopening the argument.']],
Intimacy:[['🌙 FIVE-MINUTE CLOSER','Put phones down for five minutes. Each answer: “What’s something you’ve been feeling lately that I might not know?” Either person can skip a prompt.'],['🎵 OUR CURRENT SONG','Each send one song that feels like your relationship right now. Listen before explaining why.']],
'Love Style':[['💌 LOVE, TRANSLATED','Each finish: “This week I would feel especially loved if you…” Keep it small enough to actually do.'],['🎁 $0 LOVE LANGUAGE','Plan one no-cost gesture for each other based on what makes the other feel loved. Do not reveal it until you do it.']]
};
function getScores(){return [...document.querySelectorAll('.scorebox')].map(el=>{const label=(el.childNodes[0]?.textContent||'').trim();const strong=el.querySelector('strong');return{name:label,score:parseInt(strong?.textContent)||0}}).filter(x=>BANK[x.name])}
function enhance(){const scores=getScores();if(scores.length<3)return;const challenges=[...document.querySelectorAll('.challenge')];if(!challenges.length)return;const low=[...scores].sort((a,b)=>a.score-b.score).slice(0,3);const host=challenges[0].parentElement;if(!host||host.dataset.coupleSpark==='1')return;host.dataset.coupleSpark='1';const pool=[];low.forEach(x=>BANK[x.name].forEach(c=>pool.push([x.name,...c])));const chosen=pool.slice(0,3);challenges.forEach(x=>x.remove());const intro=document.createElement('div');intro.className='challenge';intro.innerHTML='<strong>✨ Couple Spark — Match Made Moves</strong><span class="sub">Your reveal picked these from the parts of your match with the most room to grow: <b>'+low.map(x=>x.name+' '+x.score+'%').join(' • ')+'</b></span>';host.appendChild(intro);chosen.forEach(x=>{const d=document.createElement('div');d.className='challenge';d.innerHTML='<strong>'+x[1]+'</strong>'+x[2]+'<div class="tiny" style="margin-top:7px">Matched to '+x[0]+'</div>';host.appendChild(d)});const note=document.createElement('p');note.className='tiny';note.textContent='These are invitations, not assignments. Either person can skip or swap an activity.';host.appendChild(note)}
const obs=new MutationObserver(()=>enhance());obs.observe(document.getElementById('app'),{childList:true,subtree:true});enhance();
function qaButtons(){if(!qaMode)return;const q=document.getElementById('qa');if(!q||q.dataset.sparkQa)return;q.dataset.sparkQa='1';const wrap=document.createElement('div');wrap.innerHTML='<div class="tiny" style="margin-top:8px">Question Preview + Couple Spark QA</div><div class="row" id="sparkQa"></div>';q.appendChild(wrap);const preview=document.createElement('button');preview.className='btn ghost';preview.textContent='Preview Q1–Q32';preview.onclick=()=>{P=null;name='QA Preview';A=[];i=0;qScreen();enableSkip()};wrap.querySelector('#sparkQa').appendChild(preview);['Communication','Trust','Affection','Lifestyle','Future','Conflict','Intimacy','Love Style'].forEach(cat=>{const b=document.createElement('button');b.className='btn ghost';b.textContent='Low '+cat;b.onclick=()=>window.COUPLE_SPARK_QA(cat);wrap.querySelector('#sparkQa').appendChild(b)})}
function enableSkip(){if(!qaMode)return;const n=document.querySelector('[data-a="next"]');if(n){n.disabled=false;n.classList.remove('disabled');n.title='QA: skip without answering'}}
new MutationObserver(enableSkip).observe(document.getElementById('app'),{childList:true,subtree:true});
document.addEventListener('click',e=>{if(!qaMode)return;const n=e.target.closest('[data-a="next"]');if(!n||valid(A[i]))return;e.preventDefault();e.stopImmediatePropagation();if(i<Q.length-1){i++;qScreen();enableSkip()}else lock()},true);
window.COUPLE_SPARK_QA=function(cat){P={n:'QA Partner 1',a:fake(0)};ME={n:'QA Partner 2',a:fake(1)};results();setTimeout(()=>{document.querySelectorAll('.scorebox').forEach(el=>{const label=(el.childNodes[0]?.textContent||'').trim();const strong=el.querySelector('strong');const bar=el.querySelector('.bar i');const n=label===cat?22:label==='Love Style'?68:76;if(strong)strong.textContent=n+'%';if(bar)bar.style.width=n+'%'});const host=[...document.querySelectorAll('.challenge')][0]?.parentElement;if(host)delete host.dataset.coupleSpark;enhance()},0)};
setTimeout(()=>{qaButtons();enableSkip()},0);
})();